#!/bin/bash
# Example script showing how to use strategic logging for zero-shot voice cloning training

echo "Example: Training with strategic logging enabled"
echo "=============================================="
echo ""
echo "python train_v2_ddp.py \\"
echo "  --model_path /path/to/higgs-audio-model \\"
echo "  --audio_tokenizer_path /path/to/audio-tokenizer \\"
echo "  --train_data_file /path/to/chatml-training-data.json \\"
echo "  --output_dir ./training_output \\"
echo "  --per_device_train_batch_size 4 \\"
echo "  --learning_rate 1e-4 \\"
echo "  --num_train_epochs 3 \\"
echo "  --logging_steps 10 \\"
echo "  --save_steps 500 \\"
echo "  --eval_steps 500 \\"
echo "  --enable_strategic_logging \\"
echo "  --strategic_logging_steps 50 \\"
echo "  --use_lora \\"
echo "  --lora_rank 64 \\"
echo "  --lora_alpha 128 \\"
echo "  --lora_dropout 0.05"
echo ""
echo "This will enable strategic logging every 50 steps during training."
echo "The logs will help verify:"
echo "  1. Proper input processing with audio conditioning"
echo "  2. Model output quality and accuracy"
echo "  3. Shared attention mechanism in DualFFN layers"
echo "  4. Zero-shot voice cloning capabilities"